project:
  type: website
  output-dir: docs

website:
  title: "eloimm"
  navbar:
    right:
      - text: Sobre el bloc
        href: about.qmd 
      - icon: github
        href: https://github.com/eloimm
      - icon: twitter
        href: https://twitter.com/eloimm
      - icon: linkedin
        href: https://www.linkedin.com/in/eloimm/
format:
  html:
    theme: journal
    css: styles.css

editor: visual

